### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by biancadenise12** [Texxel/FontMaker#1]

**Comment by mdsimmo** [comment]
@biancadenise12 

FontMaker simply takes an image (with each character separated by white space) and outputs the .fnt file that LibGdx uses to create fonts (see the BitmapFont(FileHandle) constructor).

There's an example usage in Main.java. 

Because this program was quickly hacked together, you might need to directly alter the code in FontGenerator.writeBmpFile() to get the correct configuration.

I've updated the Readme file to be more descriptive
